version: "3.7"
services:
  db:
    hostname: db
    container_name: docker-mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    command: --disable-partition-engine-check
    restart: always
    ports:
      - "3306:3306"
         #- 192.168.10.10:3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=drupal
    volumes:
     # MySQL configuration overrides
     #- "./.docker/etc/mysql/my.cnf:/etc/mysql/conf.d/z_my.cnf"
     # Permanent DB data storage
     - /var/lib/mysql
  web:
    image: spring-boot-docker-1
    container_name: boot-rest
    depends_on:
      - db
    ports:
      - 8085:8080
      